whitepaper/astrometry.tex
Added one more additional siimulation study that needs to be done.
=> Test of pull request

whitepaper/LSST_Observing_Strategy_White_Paper.sty, whitepaper/LSST_Observing_Strategy_White_Paper.tex, whitepaper/astrometry.tex, whitepaper/cosmology.tex, whitepaper/deepdrilling.tex, whitepaper/galaxy.tex, whitepaper/lenstimedelays.tex, whitepaper/magclouds.tex, whitepaper/nonperiodictransients.tex, whitepaper/nonperiodicvariablestars.tex, whitepaper/periodictransients.tex, whitepaper/periodicvariablestars.tex, whitepaper/rollingcadence.tex, whitepaper/section-template.tex, whitepaper/solarsystem.tex, whitepaper/specialsurveys.tex, whitepaper/supernovacosmology.tex
Check out the new PDF - you should be able to move around it a bit more easily now, using the navigation bar at the end of every section. This system relies on the `\chpname` and `\secname` being defined at the start of each chapter and section, respectively - if you see a navigation bar without active hyperlinks, or that take you to the wrong place, that's probably the problem.
=> Navigation bars added to all current sections, and template.

whitepaper/galaxy.tex
Draft material for the galaxy.tex chapter.
=> Galaxy chapter draft content

commissioning/README.md, commissioning/commProp_Template.md, commissioning/commProp_r-band1hourtimeSeries.md
I have made a parallel area to the OpSim requests for idea for commissioning observations and or experiments.  These may get incorporated into a separate chapter of the white paper if the contents ends up meriting such inclusion.
Thanks,
Chuck
=> A repository for commissioning ideas

opsim/Proposal_TOOObservations.md, opsim/README.md
in response to https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/75
=> propose simulating TOO observations in OpSim

whitepaper/introduction.tex
In response to issue 61, I've added words to the introduction to explain the relationship between this document and the Science Book.
=> Added text to intro

whitepaper/gw.tex
I have created a section for GW transients. 
@drphilmarshall please approve this pull  request. thanks!
=> New Gravitational Wave section

whitepaper/supernovacosmology.tex
Tightening the text of this section - not changing the scientific content
=> Tightening text in SN cosmology section

opsim/README.md
=> fix broken links

whitepaper/authors.tex
Thanks very much for all your efforts over the last few days, everyone - it was fantastic to see how much you built together! I added everyone who made any commits to the repository as a white paper co-author. Your name in lights! :-)
=> Adding all workshop contributors to the author list!

whitepaper/authors.tex, whitepaper/galaxy.tex
First attempt to merge clarified Section 4.3 four days ago does not seem to have carried through for some reason. This is a second merge attempt. Some text in Section 4.3 was updated to clarify the approach in the chapter. 
Also took the opportunity to update Clarkson affiliation in authors.tex.
=> Milky Way: second attempt to merge updated Section 4.3; author institution update

whitepaper/MilkyWay/MW_Dust.tex, whitepaper/MilkyWay/MW_metallicity_mapping.tex, whitepaper/galaxy.tex
Corrected plane-centrism in the "Dust" subsection.
=> MW chapter; minor typo updates, consistency in subsection titles

whitepaper/supernovacosmology.tex
Edits to the text of this section, not particularly changing the content.
=> A pass through the Supernova Cosmology section

opsim/Proposal_GP.md, opsim/README.md
OpSim proposal for a run with the Galactic Plane observed at the normal
cadence.
=> Normal Plane OpSim Proposal

whitepaper/grb.tex, whitepaper/references.bib, whitepaper/transients.tex
Work-in-progress PR for GRB science (Issues #67 & #171)
=> Grb science

whitepaper/periodicpulsators.tex, whitepaper/planets.tex, whitepaper/rotationalvariables.tex, whitepaper/variables.tex, whitepaper/youngstars.tex
=> Reorganized Variables chapter 

whitepaper/MilkyWay/MW_Disk.tex, whitepaper/galaxy.tex
Preamble added in Section 4.1; material from the old Section 4.9 selected, edited a little, and added to Section 4.3; initial metrics and estimated dependencies added.
=> Milky Way chapter: updated intro, added content to Disk section

whitepaper/galaxy.tex
Chapter 4.1 - updated the introductory text, fixed some subsection references; updated author list to include the authors of the old Chapter 5 in preparation for that material to be merged with Chapter 4.
=> Fixed subsection references in galaxy.tex, updated intro pre-amble

whitepaper/MilkyWay/MW_Disk.tex
Slight re-wording of some text in science motivation; included a little more information about the proposed metrics.
=> Minor updates to MW_Disk.tex

whitepaper/MilkyWay/MW_Halo.tex
Introduction and target description. Still needs reference
=> Updating Halo sub-section in Chapter 4

whitepaper/AGN/AGN_BELR.tex, whitepaper/AGN/AGN_Census.tex, whitepaper/AGN/AGN_Disk_Intrinsic.tex, whitepaper/agn.tex
Hi @drphilmarshall please merge my most recent updates
=> Updated text and metrics in AGN chapter

whitepaper/MilkyWay/MW_Astrometry_Skeleton.tex
As a backup should we want to revert, this is a blank subsection for the MW_Astrometry subsection in the same format as all the other subsections.
=> MW_Astrometry_Skeleton.tex added

whitepaper/MilkyWay/MW_Astrometry.tex
Small edits to MW_Astrometry.tex (now Section 4.6) to flow better with chapter structure
=> Light editing of MW_Astrometry.tex to fit Chapter 4 structure

whitepaper/transients.tex
Added line for X-ray novae (hundreds could be present in LSST data if current thinking on selection effects against short period systems is correct) and changed cataclysmic variables line to reflect dwarf novae in addition to flares.
=> Update table 1

whitepaper/MilkyWay/MW_Disk.tex
light edits to Plane section, including added discussion of proposed OpSim run
=> plane edits

whitepaper/Makefile, whitepaper/MilkyWay/MW_Halo.tex, whitepaper/authors.tex
Also worked on the description of the main sequence stars sample.
=> Description of star/galaxy separation metric in MW_Halo.

whitepaper/MilkyWay/MW_Astrometry.tex
Large changes to astrometry section—now have clear science cases
=> Astrometry section changes

whitepaper/MilkyWay/MW_Astrometry.tex
A few minor updates to the text; added @willclarkson and @yoachim to section author list
=> minor updates to 4.3.3. text

whitepaper/MilkyWay/MW_Astrometry.tex
Minor typo fix to section 4.4.3 (astrometry OpSim analysis)
=> Typo fix, section 4.4.3

whitepaper/galaxy.tex
Clarification on the structure of the MW chapter and on the distinction between Metric and figure of merit, and a request for help from readers.
=> In the MW chapter preamble (4.1), clarified terminology and structure

whitepaper/MilkyWay/MW_Disk.tex
MW Chapter 4.3 (MW Disk): Clarified the language (Figure of Merit vs Metric); moved the comment about enigma_1189 to the Discussion section; added text requesting effort to implement the FoMs for the science cases in this chapter.
=> MW Disk chapter (4.3): presentability edits

whitepaper/MilkyWay/MW_Disk.tex, whitepaper/galaxy.tex
Two more minor edits, 4.1 and 4.3
=> Presentability updates 4.1 and 4.3

whitepaper/MilkyWay/MW_Halo.tex
Replaced placeholder quantities XX with estimates from the literature (RR Lyrae amplitudes; distance out to which streams are expected). A few minor typo fixes. Removed request for co-author to add content.
=> Chapter 4.2 presentability updates

whitepaper/MilkyWay/MW_Halo.tex
One more... replaced "Chapter XX" --> chapter reference.
=> 4.2 Chapter reference update

whitepaper/MilkyWay/MW_Astrometry.tex
=> 4.4 subsection heading typo fix

whitepaper/LSST_Observing_Strategy_White_Paper.sty, whitepaper/SpecialSurveys/solar_system_specials.tex, whitepaper/references.bib, whitepaper/solarsystem.tex
@rhiannonlynne @davidtrilling could you take a look a these edits?
=> Solar System detecting activity section

whitepaper/MilkyWay/MW_Astrometry.tex, whitepaper/MilkyWay/MW_Disk.tex
I have re-run the Galactic Supernova figure of merit on minion_1016 and minion_1020. This pull request updates the numbers in the discussion and Table.
=> GalacticSupernova FoM result updated for 2016 OpSim runs

whitepaper/galaxy.tex
@akvivas here's the updated intro to galaxy.tex we talked about. Let me know if you have comments! 
Thanks, Will
=> Updated the introduction to galaxy.tex

whitepaper/MilkyWay/MW_Halo.tex
Unfortunately I won't have the metric ready in time for the first release of the
whitepaper, so I've changed the text to acknowledge that it is an ongoing
effort.
=> Acknowlege that star-galaxy metric is not finished.

whitepaper/MilkyWay/MW_Disk.tex
In preparation for replacing the bullet-point lists of the Figures of Merit with more useful descriptions, I have added some text to Section 4.3.2 (Figures of Merit discussion). I will work on translating the notes for the individual FoMs into tables of steps next.
for interest: @akvivas @cbritt4 @caprastro
=> MW_Disk.tex: updating discussion of Figures of Merit

whitepaper/authors.tex, whitepaper/eruptive.tex, whitepaper/gw.tex, whitepaper/transients.tex
=> transients cleanup

whitepaper/youngstars.tex
@phartigan your youngstars.tex should now be in the repository.
=> youngstars.tex: fixed typos & figure references

whitepaper/youngstars.tex
Whoops, runaway boldface... fixed.
=> runaway \bf fixed in youngstars.tex

whitepaper/MilkyWay/MW_Astrometry.tex, whitepaper/MilkyWay/MW_Disk.tex, whitepaper/MilkyWay/MW_Dust.tex, whitepaper/MilkyWay/MW_Future.tex, whitepaper/MilkyWay/MW_Halo.tex, whitepaper/MilkyWay/MW_SFH.tex, whitepaper/authors.tex, whitepaper/galaxy.tex
New authors added to authors.tex:
Victor Debattista
John Gizis
Mike Liu
cc @akvivas
=> Updated author entries in Galaxy chapter

whitepaper/MilkyWay/MW_Disk.tex
Discussion of Figures of Merit for Microlensing in the Milky Way from the main survey, has been added to the Milky Way chapter, section 4.3.2. 
Input from microlens experts on this section would be very valuable!! 
cc @mtpenny @davidpbennett @jasondrhodes & Rachel Street 
cc @akvivas
=> Microlensing FoM discussion added to 4.3.2

whitepaper/MilkyWay/MW_Astrometry.tex, whitepaper/MilkyWay/MW_Disk.tex, whitepaper/MilkyWay/MW_Dust.tex, whitepaper/MilkyWay/MW_Halo.tex
Now that the Wide-Fast-Deep Plane OpSim run has been performed, a summary column for that run has been added to the Summary tables in Chapter 4. Its values will be filled in as the FoMs are evaluated for that run.
=> MW_*.tex: added column for WFD-Plane in summary tables

whitepaper/transients.tex
=> Edit transients intro.

whitepaper/MilkyWay/MW_Disk.tex
Hopefully this will reduce confusion in the confusion paragraph... :/
=> Typo fix in source-confusion para

whitepaper/Cosmology/supernovacosmology.tex
modified:   supernovacosmology.tex
=> Minor changes

whitepaper/WFIRST/WFIRST_microlensing.tex, whitepaper/WFIRST/WFIRST_weaklensing.tex, whitepaper/wfirst.tex
made some editing changes to wfirst.tex and weaklensing and microlensing
=> changed WFIRST files

whitepaper/Variables/youngstars.tex
merged yso section.  The mini-survey can be cut out and repositioned elsewhere in the document
as required
=> update yso section

whitepaper/MilkyWay/MW_Astrometry.tex
Section 4.3.2. just after the itemized list of Astrometry metrics: I have added some discussion of what the implemented versions of metrics A and B are doing.
@yoachim @dgmonet
=> Astrometry: update discussion of parallax-DCR and parallax coverage

whitepaper/MilkyWay/MW_Astrometry.tex
After feedback from @yoachim , updates made to the new paragraphs in 4.3.2 (Astrometry metric description).
=> Astrometry: Correction to 4.3.2 metric description

whitepaper/MilkyWay/MW_Astrometry.tex
Issue #430 
Sentence tidying for metric B; removed the \new{} tag from material added in the past week
@lundmb
=> 4.3 - Minor corrections, removal of \new{} tag

whitepaper/MilkyWay/MW_Disk.tex
Working toward issue #430 - I have attemped to clarify the discussion about the Galactic Supernova FoM: PanSTARRS-like cadence is better by this FoM but ignores some of the spatial regions covered by baseline so perhaps that's not surprising. 
@bethwillman cc @akvivas
=> Slight modification of Galactic Supernova FoM (Issue 430)

whitepaper/MilkyWay/MW_FutureWork.tex, whitepaper/MilkyWay/MW_Halo.tex, whitepaper/galaxy.tex
Working towards issue #430 - commented Dust out for the moment (similar to Science Book); reinstated MW_Halo.tex; minor update to chapter introduction to include ref to MW_Halo.tex.
@bethwillman @akvivas
=> Commented Dust; reinstated MW_Halo

whitepaper/MilkyWay/MW_Disk.tex, whitepaper/references.bib
=> Two sentences on Difference Imaging added; 3 refs

whitepaper/Variables/multiperiodicpulsators.tex
Updated based on recent feedback.
=> Updated multi-periodic pulsators subsection

commissioning/fraserw_commiss
This is a first draft of Wes's cadence commissioning proposal
=> Wes's commissioning proposal

whitepaper/LSST_Observing_Strategy_White_Paper.tex
@ivezic Would you mind taking a look at my changes please, and making sure they sound OK? I'm trying to make it clear that this is not an official project document while acknowledging the support the project has provided. The preface also now tries to explain the audience as well - if you have better words for how the project will read the white paper please let me know and I'll work them in. Thanks!
=> Small changes to preface and title page in response to some project/sci collabs confusion

whitepaper/AGN/AGN_BELR.tex, whitepaper/AGN/AGN_Census.tex, whitepaper/AGN/AGN_Clustering.tex, whitepaper/AGN/AGN_Disk_Extrinsic.tex, whitepaper/AGN/AGN_Disk_Intrinsic.tex, whitepaper/AGN/AGN_Future_Work.tex, whitepaper/agn.tex, whitepaper/authors.tex, whitepaper/references.bib
The changes are based on Lynne Jones' review of section 8.2
=> Revisions to AGN chapter introduction & AGN census science with LSST

opsim/Proposal_Euclid.md
Add opsim proposal for survey that will extend to Dec +30 with 10 visits in ugrizy and no pairs of visits
=> Add Euclid proposal

whitepaper/MilkyWay/MW_Disk.tex
Attempts at the conclusions for Section 4.2 (Milky Way Disk) have been input to chapter 4.2. All the feedback received thus far on this has been incorporated. 
@cbritt4, @caprastro, @akvivas and any other interested authors, please review this new material and suggest any edits you might have.
=> 10 conclusion answers for Section 4.2

whitepaper/AGN/AGN_Disk_Intrinsic.tex, whitepaper/references.bib
Hi Dr Marshall,
I've added responses to Zeljko's 10 questions!
=> Answered Zelko's 10 questions

whitepaper/MilkyWay/MW_Astrometry.tex
Initial answers provided to the 10 questions for Chapter 4.3 (Milky Way: Astrometry). Co-authors, please comment and update if necessary.
=> MW_Astrometry: 10 conclusion answers

whitepaper/MilkyWay/MW_Astrometry.tex
Updated the answers to the 10 conclusion questions in MW_Astrometry (Section 4.3) to reflect co-author input Sat Jan 28.
=> MW_Astrometry: 10 answers update

whitepaper/MilkyWay/MW_Astrometry.tex
Thanks to Dana Casetti for input, which is merged into "Answer 1" in the conclusions.
=> MW_Astrometry: Answer 1 updated to include proper motion zeropoints

whitepaper/Variables/multiperiodicpulsators.tex, whitepaper/references.bib
I answered Zeljko's 10 questions for the subsection on multi-periodic pulsators.  I also made small improvements throughout the section to make the case clearer and stronger.
=> Answer 10 questions for Section 5.3, multi-periodic pulsators

whitepaper/Transients/grb.tex
=> conclusions section

whitepaper/Cosmology/supernovacosmology.tex
modified:   supernovacosmology.tex
Adding text for @jhrlsst answering Zeljko's 10 questions.
=> pushing file for @jhrlsst due to technical issues

whitepaper/Variables/multiperiodicpulsators.tex
Added information to Q 5, 6 and 8 in conclusion of multi-periodic variables.
=> Additional answers to ten questions in Variable Stars

whitepaper/authors.tex
Added institutional details for myself.
=> Added institutional details

whitepaper/introduction.tex
This is in response to #522 
@bethwillman What do you think? If you click on the "Files Changed" tab you can see what I did, and then use the code review mechanism to either comment, approve or request changes. Thanks!
=> New empty subsection for how our findings could influence the observing schedule

whitepaper/cadexp2.tex, whitepaper/introduction.tex, whitepaper/rollingcadence.tex, whitepaper/tradeoffs.tex
This is in response to #494 - @ivezic, I made a space for you to add your text in `tradeoffs.tex` in this branch (`issue/494/conclusions`). Let's add in any other commentary in the second "Conclusions from the Science Cases" section, and then see whether we can spread this over the rest of the chapter, merging with Steve's existing thoughts. I'm happy to do this once you've uploaded your work. If you can add in @connolly 's notes as well that would be most helpful. Thanks! I'll assign a reviewer (probably @bethwillman) when we've pulled everything together.
=> Conclusions chapter (with Tensions and Tradeoffs)

whitepaper/agn.tex, whitepaper/cosmology.tex, whitepaper/galaxy.tex, whitepaper/magclouds.tex, whitepaper/solarsystem.tex, whitepaper/specialsurveys.tex, whitepaper/transients.tex, whitepaper/variables.tex
=> Commented out placeholder summary text

README.md
=> Fixed README to point to guidelines in introduction, not preface

whitepaper/authors.tex, whitepaper/transients.tex
=> fix broken transient author

whitepaper/Cosmology/supernovacosmology.tex, whitepaper/authors.tex
modified:   Cosmology/supernovacosmology.tex
modified:   authors.tex
=> Added author requests to SN sections

whitepaper/tradeoffs.tex
Added a sentence with the main LSS conclusion: 
"The large-scale structure studies are area-limited more than depth-limited and 
thus a larger sky coverage is preferred."
=> added LSS conclusion about larger sky area

whitepaper/SolarSystem/SolarSystem_CometActivity.tex, whitepaper/SolarSystem/SolarSystem_OrbitalAccuracy.tex
took a stab at fixing the typos spotted by reviewer in #612
=> fixed typos spotted in #612

whitepaper/WFIRST/WFIRST_microlensing.tex, whitepaper/authors.tex, whitepaper/references.bib
modified:   WFIRST/WFIRST_microlensing.tex
Equations removed and text rewritten accordingly to address Anze Slosar comments
modified:   authors.tex
modified:   references.bib
@rpoleski @davidpbennett should review the changes
=> Addressing issue #622 for WFIRST microlensing section

whitepaper/Cosmology/supernovacosmology.tex
=> Made David's suggested changes

whitepaper/cadexp2.tex, whitepaper/rollingcadence.tex
Here are my edits for Chapter 2 as per the request to be reviewer.
=> Chapter 2 edits, from LSST Pub Board Reviewer Michael Reuter

whitepaper/WFIRST/WFIRST_supernovae.tex
I added the responses to the questions that I e-mailed around. Also added FoM numbers.
=> wfirst SN section updated

whitepaper/MilkyWay/MW_Disk.tex, whitepaper/Variables/multiperiodicpulsators.tex, whitepaper/cadexp2.tex, whitepaper/tradeoffs.tex
From @ivezic , addressing #652
=> Double u-band exposure OpSim run clean-up

whitepaper/SolarSystem/SolarSystem_AsteroidLightCurves.tex, whitepaper/SolarSystem/SolarSystem_CometActivity.tex, whitepaper/SolarSystem/SolarSystem_Discovery.tex, whitepaper/SolarSystem/SolarSystem_PHA.tex, whitepaper/SpecialSurveys/solar_system_specials.tex, whitepaper/references.bib
=> Solar System specials & chapter edits

whitepaper/AGN/AGN_Census.tex
@gtrichards Thanks for sending your more detailed conclusions - I've added them in, see the Files Changed tab if you want to make sure that things are OK.
=> More detailed conclusions, from Gordon Richards
